plugins { id 'com.android.application' }
android {
    namespace 'pl.onkyo.remote.touchprobe'
    compileSdk 36
    defaultConfig {
        applicationId 'pl.onkyo.remote.touchprobe'
        minSdk 36
        targetSdk 36
        versionCode 1
        versionName '0.1'
        testInstrumentationRunner 'pl.onkyo.remote.touchprobe.TouchProbeRunner'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
