plugins {
    id 'com.android.application'
}

android {
    namespace 'pl.onkyo.remote'
    compileSdk 36

    defaultConfig {
        applicationId 'pl.onkyo.remote'
        minSdk 26
        targetSdk 36
        versionCode 8
        versionName '0.4.3'
        testInstrumentationRunner 'pl.onkyo.remote.WidgetSmokeTestRunner'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
